name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get packr
        run: go install github.com/gobuffalo/packr/v2/packr2@v2.8.3

      - name: Get tag
        uses: olegtarasov/get-tag@v2.1.2
        id: tagName

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Put artifacts into a single zip
        run: |
          make build
          zip json_exporter.zip json_exporter

      - name: Publish zip into release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "json_exporter.zip"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.tagName.outputs.tag }}
        